"use strict";

exports.__esModule = true;
exports.DEFAULT_POSITION = exports.DEFAULT_LOADING_DURATION = exports.DEFAULT_INTERVAL = exports.DEFAULT_DURATION = exports.DEFAULT_DOWNLOADING_DURATION = exports.DEFAULT_COUNTDOWN_DURATION = exports.COUNTDOWN_STROKE_WIDTH = exports.COUNTDOWN_SIZE = exports.COUNTDOWN_RADIUS = void 0;
var _propsType = require("../props-type");
var DEFAULT_DURATION = exports.DEFAULT_DURATION = 2000;
var DEFAULT_POSITION = exports.DEFAULT_POSITION = _propsType.SnackbarPosition.bottom;
var DEFAULT_INTERVAL = exports.DEFAULT_INTERVAL = 250;
var DEFAULT_COUNTDOWN_DURATION = exports.DEFAULT_COUNTDOWN_DURATION = 5000;
var DEFAULT_LOADING_DURATION = exports.DEFAULT_LOADING_DURATION = 5000;
var DEFAULT_DOWNLOADING_DURATION = exports.DEFAULT_DOWNLOADING_DURATION = 5000;
var COUNTDOWN_SIZE = exports.COUNTDOWN_SIZE = 24;
var COUNTDOWN_STROKE_WIDTH = exports.COUNTDOWN_STROKE_WIDTH = 2;
var COUNTDOWN_RADIUS = exports.COUNTDOWN_RADIUS = 12;