import { SnackbarPosition } from "../props-type";
export var DEFAULT_DURATION = 2000;
export var DEFAULT_POSITION = SnackbarPosition.bottom;
export var DEFAULT_INTERVAL = 250;
export var DEFAULT_COUNTDOWN_DURATION = 5000;
export var DEFAULT_LOADING_DURATION = 5000;
export var DEFAULT_DOWNLOADING_DURATION = 5000;
export var COUNTDOWN_SIZE = 24;
export var COUNTDOWN_STROKE_WIDTH = 2;
export var COUNTDOWN_RADIUS = 12;